// Auto-generated by obj2offsets.py — do not edit by hand
// OBJ:  character_16x16.obj
// MAP:  character.png
//
// Vertex bounds:  X [-0.062500 → 0.062500]  Z [-0.062500 → 0.062500]
// World size:     0.125000 × 0.125000
// Tile grid:      16 × 16

#ifndef CHARACTER_OFFSETS_H
#define CHARACTER_OFFSETS_H

#define TILE_SIZE      0.007812f  // world_width / tile_cols
#define WORLD_OFFSET_X 0.062500f  // -minX
#define WORLD_OFFSET_Z 0.062500f  // -minZ

// Debug print — paste into your game loop to verify:
// iprintf("\x1b[21;0Htile(x,z): %d, %d",
//     (int)((charPos.x + WORLD_OFFSET_X) / TILE_SIZE),
//     (int)((charPos.z + WORLD_OFFSET_Z) / TILE_SIZE));

#endif // CHARACTER_OFFSETS_H
