// Auto-generated by obj2offsets.py — do not edit by hand
// OBJ:  iwatodaiDorm_256x256.obj
// MAP:  iwatodaiDorm_0_0_64_64.png
//
// Vertex bounds:  X [-1.812500 → 0.937500]  Z [-1.687500 → 0.375000]
// World size:     2.750000 × 2.062500
// Tile grid:      64 × 64

#ifndef IWATODAIDORM_OFFSETS_H
#define IWATODAIDORM_OFFSETS_H

#define TILE_SIZE      0.042969f  // world_width / tile_cols
#define WORLD_OFFSET_X 1.812500f  // -minX
#define WORLD_OFFSET_Z 1.687500f  // -minZ

// Debug print — paste into your game loop to verify:
// iprintf("\x1b[21;0Htile(x,z): %d, %d",
//     (int)((charPos.x + WORLD_OFFSET_X) / TILE_SIZE),
//     (int)((charPos.z + WORLD_OFFSET_Z) / TILE_SIZE));

#endif // IWATODAIDORM_OFFSETS_H
