#include <nds.h>
#include "demo_dialogue.h"

// Auto-generated by dialogue_compiler.py — do not edit by hand
// Scene: demo

// ── Shared BG slot ──────────────────────────────────────────────────
int demo_dialogue_bg_slot = 0;

// ── BG imports ──────────────────────────────────────────────────────
#include "bgAkihiko.h"

void demo_unload() {
    bgHide(demo_dialogue_bg_slot);
    // TODO: free VRAM / reset loaders if needed.
}

// ════════════════════════════════════════════════════════════════
// interaction: merchant_greeting — Travelling merchant near the east gate
// ════════════════════════════════════════════════════════════════

const char* demo_merchant_greeting_bg_names[1] = { "bgAkihiko" };
void (*demo_merchant_greeting_bg_loaders[1])() = {
    nullptr,  // [0] bgAkihiko
};

void demo_merchant_greeting_load_bg(int bgIndex) {
    if (bgIndex >= 0 && bgIndex < 1 && demo_merchant_greeting_bg_loaders[bgIndex])
        demo_merchant_greeting_bg_loaders[bgIndex]();
}

void demo_merchant_greeting_load() {
    // Use demo_dialogue_bg_slot as the target hardware slot.
    
    demo_merchant_greeting_bg_loaders[0] = [](){
        dmaCopy(bgAkihikoTiles,
            bgGetGfxPtr(demo_dialogue_bg_slot),
            bgAkihikoTilesLen);
        dmaCopy(bgAkihikoMap,
            bgGetMapPtr(demo_dialogue_bg_slot),
            bgAkihikoMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgAkihikoPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgAkihikoPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(demo_dialogue_bg_slot);
    };

    demo_merchant_greeting_init();
}

dialogue demo_merchant_greeting_lines[14];

void demo_merchant_greeting_init() {
    dialogueSelection demo_merchant_greeting_sel_2_0 = { "What kind of curiosities?", false, &demo_merchant_greeting_lines[3] };
    dialogueSelection demo_merchant_greeting_sel_2_1 = { "Tell me about the maps.", false, &demo_merchant_greeting_lines[9] };
    dialogueSelection demo_merchant_greeting_sel_2_2 = { "Just browsing, thanks.", false, &demo_merchant_greeting_lines[12] };
    dialogueSelection demo_merchant_greeting_sel_6_0 = { "How much?", false, &demo_merchant_greeting_lines[7] };
    dialogueSelection demo_merchant_greeting_sel_6_1 = { "No thanks.", false, &demo_merchant_greeting_lines[12] };

    demo_merchant_greeting_lines[0] = { "Merchant", "Welcome, welcome! Looking for anything in particular?", 0 /* bgAkihiko */, NULL, &demo_merchant_greeting_lines[1], {} };
    demo_merchant_greeting_lines[1] = { "Merchant", "I've got maps, dried goods, and a few... curiosities.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[0], &demo_merchant_greeting_lines[2], {} };
    demo_merchant_greeting_lines[2] = { "Merchant", "What catches your eye?", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[1], NULL, { demo_merchant_greeting_sel_2_0, demo_merchant_greeting_sel_2_1, demo_merchant_greeting_sel_2_2 } };
    demo_merchant_greeting_lines[3] = { "Merchant", "Ah, a person of taste!", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[2], &demo_merchant_greeting_lines[4], {} };  // @merch_curious
    demo_merchant_greeting_lines[4] = { "Merchant", "I've got a compass that always points to your greatest regret.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[3], &demo_merchant_greeting_lines[5], {} };
    demo_merchant_greeting_lines[5] = { "Merchant", "Terrible for navigation. Wonderful for drama.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[4], &demo_merchant_greeting_lines[6], {} };
    demo_merchant_greeting_lines[6] = { "Merchant", "Interested?", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[5], NULL, { demo_merchant_greeting_sel_6_0, demo_merchant_greeting_sel_6_1 } };
    demo_merchant_greeting_lines[7] = { "Merchant", "For you? Three silver.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[6], &demo_merchant_greeting_lines[8], {} };  // @merch_price
    demo_merchant_greeting_lines[8] = { "Merchant", "Or one favour. I'll let you decide which is cheaper.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[7], &demo_merchant_greeting_lines[9], {} };
    demo_merchant_greeting_lines[9] = { "Merchant", "Best maps this side of the river!", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[8], &demo_merchant_greeting_lines[10], {} };  // @merch_maps
    demo_merchant_greeting_lines[10] = { "Merchant", "I've got the eastern districts, old town routes, even the underground canals.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[9], &demo_merchant_greeting_lines[11], {} };
    demo_merchant_greeting_lines[11] = { "Merchant", "The canal map's not strictly... legal to own. But that's between us.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[10], &demo_merchant_greeting_lines[12], {} };
    demo_merchant_greeting_lines[12] = { "Merchant", "No trouble at all. Come back anytime!", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[11], &demo_merchant_greeting_lines[13], {} };  // @merch_bye
    demo_merchant_greeting_lines[13] = { "Merchant", "I'll be here until the lanterns go out.", 0 /* bgAkihiko */, &demo_merchant_greeting_lines[12], NULL, {} };
}
