#pragma once
// Auto-generated by dialogue_compiler.py — do not edit by hand
// Scene: demo

#include "controllers/DialogueController.h"

// ── Shared BG slot ──────────────────────────────────────────────────
// All dialogue bgs are swapped in/out of this one hardware slot.
// Assign this before calling any interaction _load():
//   demo_dialogue_bg_slot = bgInit(3, BgType_Text8bpp, BgSize_T_256x256, 0, 1);
extern int demo_dialogue_bg_slot;

void  demo_unload();  // stub: hide/free the slot

// ── interaction: merchant_greeting — Travelling merchant near the east gate
//    bgs (1): [0]=bgAkihiko
extern const char*  demo_merchant_greeting_bg_names[1];
extern void        (*demo_merchant_greeting_bg_loaders[1])();
void  demo_merchant_greeting_load_bg(int bgIndex);
extern dialogue demo_merchant_greeting_lines[14];
void  demo_merchant_greeting_init();
void  demo_merchant_greeting_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* demo_merchant_greeting_first() { return &demo_merchant_greeting_lines[0]; }
inline dialogue* demo_merchant_greeting_merch_curious() { return &demo_merchant_greeting_lines[3]; }
inline dialogue* demo_merchant_greeting_merch_price() { return &demo_merchant_greeting_lines[7]; }
inline dialogue* demo_merchant_greeting_merch_maps() { return &demo_merchant_greeting_lines[9]; }
inline dialogue* demo_merchant_greeting_merch_bye() { return &demo_merchant_greeting_lines[12]; }

// Initialise every interaction's struct arrays (call after all _load()s).
inline void demo_init_all() {
    demo_merchant_greeting_init();
}
