// ============================================================
// MP3 playback demo for Nintendo DS using libmad
// ARM9 side: decodes MP3 → PCM, hands to libnds sound API
// ARM7 side: handled by default libnds ARM7 binary (no custom code needed)
// ============================================================

#include <nds.h>
#include <mad.h>
#include <stdio.h>
#include "core/globals.h"
#include "MusicView.h"

// This header is auto-generated by the build system from audio/your_track.mp3
// The name is derived from the filename: spaces/dots become underscores
#include "song_mp3.h"

// ------------------------------------------------------------
// Double-buffer setup
// The ARM9 decodes into the INACTIVE buffer while the ARM7
// plays the ACTIVE buffer. We swap them when the active one finishes.
// 2304 samples = exactly 2 MP3 frames worth, keeps latency low.
// ------------------------------------------------------------
#define PCM_BUFFER_SAMPLES  2304            // samples per buffer (per channel)
#define PCM_BUFFER_BYTES    (PCM_BUFFER_SAMPLES * sizeof(s16))

// Two stereo interleaved buffers: [L, R, L, R, ...]
// Must be in main RAM (not DTCM) so the ARM7 can DMA from it
s16 pcmBuffer[2][PCM_BUFFER_SAMPLES * 2];  // *2 for stereo interleave
volatile int activeBuffer  = 0;            // which buffer ARM7 is currently playing
volatile int fillPos       = 0;            // write cursor into inactive buffer
volatile bool bufferReady  = false;        // true when inactive buffer is full

// libmad state — keep alive for the entire song (stores decoder state between frames)
struct mad_stream madStream;
struct mad_frame  madFrame;
struct mad_synth  madSynth;

// ------------------------------------------------------------
// Convert libmad's 32-bit fixed-point sample to signed 16-bit PCM
// MAD_F_FRACBITS = 28, so we shift right by 13 (28 - 15 = 13)
// to map into the s16 range [-32768, 32767]
// ------------------------------------------------------------
inline s16 fixedToS16(mad_fixed_t sample) {
    // Clip to [-1.0, 1.0] in fixed point before converting
    if (sample >= MAD_F_ONE)  return 32767;
    if (sample <= -MAD_F_ONE) return -32768;
    return (s16)(sample >> (MAD_F_FRACBITS - 15));
}

// ------------------------------------------------------------
// Initialise libmad and point it at the embedded MP3 data
// ------------------------------------------------------------
void mp3Init() {
    mad_stream_init(&madStream);
    mad_frame_init(&madFrame);
    mad_synth_init(&madSynth);

    // Tell libmad where the MP3 data is and how long it is.
    // For embedded data this is the whole file up front.
    // For streaming from filesystem you'd feed chunks here instead.
    mad_stream_buffer(&madStream, song_mp3, song_mp3_size);
}

// ------------------------------------------------------------
// Decode one MP3 frame and write resulting PCM into inactive buffer.
// One MP3 frame = 1152 PCM samples per channel.
// Call this repeatedly until it returns false (end of file / error).
// ------------------------------------------------------------
bool mp3DecodeFrame() {
    // Attempt to decode the next MP3 frame
    if (mad_frame_decode(&madFrame, &madStream) != 0) {
        if (MAD_RECOVERABLE(madStream.error)) {
            // Recoverable errors (e.g. bad sync byte, ID3 tag in stream)
            // are common and harmless — just skip and continue
            return true;
        }
        // MAD_ERROR_BUFLEN means we ran out of data → end of file
        // Any other non-recoverable error → stop decoding
        return false;
    }

    // Synthesize: convert the decoded frame into PCM samples
    // This is the CPU-heavy step
    mad_synth_frame(&madSynth, &madFrame);

    // madSynth.pcm.length = number of samples decoded (usually 1152)
    // madSynth.pcm.samples[0] = left channel  (mad_fixed_t = 32-bit fixed point)
    // madSynth.pcm.samples[1] = right channel (same as [0] if mono)
    bool isStereo = (madSynth.pcm.channels == 2);

    // Write decoded samples into the INACTIVE buffer (not the one ARM7 is playing)
    s16* inactive = pcmBuffer[1 - activeBuffer];

    for (int i = 0; i < (int)madSynth.pcm.length; i++) {
        s16 left  = fixedToS16(madSynth.pcm.samples[0][i]);
        s16 right = isStereo
                  ? fixedToS16(madSynth.pcm.samples[1][i])
                  : left;  // mono: duplicate left channel to right

        // Interleave stereo: L R L R L R ...
        inactive[fillPos++] = left;
        inactive[fillPos++] = right;

        // Buffer full — mark it ready for playback and reset cursor
        if (fillPos >= PCM_BUFFER_SAMPLES * 2) {
            bufferReady = true;
            fillPos = 0;
            return true;
        }
    }

    return true;
}

// ------------------------------------------------------------
// Kick off playback of the filled buffer using libnds sound API.
// soundPlaySample() tells the default ARM7 binary to start a
// DMA transfer from our PCM buffer into the sound hardware.
// No custom ARM7 code needed — libnds handles the IPC for us.
// ------------------------------------------------------------
int soundChannel = -1;

void startPlayback(int sampleRate) {
    s16* buf = pcmBuffer[activeBuffer];

    // Stop previous channel if one is running
    if (soundChannel >= 0) soundKill(soundChannel);

    // SoundFormat_16Bit = signed 16-bit PCM
    // The buffer contains interleaved stereo samples
    soundChannel = soundPlaySample(
        buf,
        SoundFormat_16Bit,
        PCM_BUFFER_SAMPLES * 2 * sizeof(s16),  // total bytes in buffer
        sampleRate,                              // e.g. 44100 or 22050
        127,                                     // volume (0-127)
        64,                                      // panning (64 = centre)
        false,                                   // loop? no — we manage looping ourselves
        0                                        // loop point
    );
}

// ------------------------------------------------------------
// Clean up libmad state
// ------------------------------------------------------------
void mp3Cleanup() {
    mad_synth_finish(&madSynth);
    mad_frame_finish(&madFrame);
    mad_stream_finish(&madStream);
    if (soundChannel >= 0) soundKill(soundChannel);
}

void MusicView::Init() {
    // // set video mode for 3 text layers and 1 extended rotation layer
	// videoSetMode(MODE_3_2D);
	// // set sub video mode for 4 text layers
	// videoSetModeSub(MODE_0_2D);
    
    // Standard DS init
    consoleDemoInit();  // sets up printf on bottom screen

    iprintf("MP3 Demo\n");
    iprintf("Initialising...\n");

    // Initialise the libnds sound system (sets up ARM7 communication)
    soundEnable();

    // Point libmad at our embedded MP3 data
    mp3Init();

    iprintf("Decoding first buffer...\n");

    // Pre-fill the first buffer before starting playback so there's
    // no gap at the start — decode frames until buffer is full
    while (!bufferReady) {
        if (!mp3DecodeFrame()) {
            iprintf("Error or empty file!\n");
            while(1) swiWaitForVBlank();
        }
    }
    bufferReady = false;

    // Start playing the first filled buffer
    sampleRate = madSynth.pcm.samplerate;
    iprintf("Sample rate: %d Hz\n", sampleRate);
    iprintf("Playing...\n");

    startPlayback(sampleRate);
}

ViewState MusicView::Update() {
    swiWaitForVBlank();
    scanKeys();

    // START = quit
    if (keysDown() & KEY_START) {
        return ViewState::MAIN_MENU;
    };

    // Decode into the inactive buffer while the active one plays.
    // When the inactive buffer fills up, swap and restart playback.
    // This is the double-buffer / ping-pong pattern.
    if (!bufferReady) {
        // Decode several frames per vblank to keep up with playback.
        // At 44100Hz, 60fps vblank, we need ~735 samples/frame.
        // Each MP3 frame gives 1152 samples, so 1 frame/vblank is enough,
        // but we do a few to be safe and reduce risk of buffer underrun.
        for (int i = 0; i < 3; i++) {
            if (!mp3DecodeFrame()) {
                // End of file — stop playback
                iprintf("\nFinished!\n");
                mp3Cleanup();
                while(1) swiWaitForVBlank();
            }
            if (bufferReady) break;
        }
    }

    // If we just finished filling the inactive buffer, swap and play it
    if (bufferReady) {
        bufferReady  = false;
        activeBuffer ^= 1;          // flip: inactive becomes active
        startPlayback(sampleRate);  // restart playback from newly active buffer
        iprintf(".");               // progress indicator
    }
    return ViewState::KEEP_CURRENT;
}

void MusicView::Cleanup() {
    // clear screen
    setBrightness(3, 0);
    consoleClear();

    // reset music
    mp3Cleanup();
}