// ============================================================
// MP3 playback demo for Nintendo DS using libmad + Maxmod
// ARM9 side: decodes MP3 → PCM via Maxmod stream callback
// ARM7 side: playback handled automatically by Maxmod
// ============================================================

#include <nds.h>
#include <maxmod9.h>
#include <mad.h>
#include <stdio.h>
#include "core/globals.h"
#include "MusicView.h"

// This header is auto-generated by the build system from audio/your_track.mp3
#include "song_mp3.h"

struct mad_stream madStream;
struct mad_frame  madFrame;
struct mad_synth  madSynth;

// ------------------------------------------------------------
// Intermediate Sample Buffer
// Holds leftover samples from libmad if Maxmod didn't need a full frame
// ------------------------------------------------------------
#define MAX_SAMPLES_PER_FRAME 1152             // libmad max output per frame
s16 leftoverBuffer[MAX_SAMPLES_PER_FRAME * 2]; // * 2 for stereo interleaved
int leftoverCount = 0;                         // Number of sample PAIRS available
int leftoverIndex = 0;                         // Current read position

// ------------------------------------------------------------
// Convert libmad's 32-bit fixed-point sample to signed 16-bit PCM
// ------------------------------------------------------------
inline s16 fixedToS16(mad_fixed_t sample) {
    if (sample >= MAD_F_ONE)  return 32767;
    if (sample <= -MAD_F_ONE) return -32768;
    return (s16)(sample >> (MAD_F_FRACBITS - 15));
}

// ------------------------------------------------------------
// Initialise libmad
// ------------------------------------------------------------
void mp3Init() {
    mad_stream_init(&madStream);
    mad_frame_init(&madFrame);
    mad_synth_init(&madSynth);

    mad_stream_buffer(&madStream, song_mp3, song_mp3_size);
}

// ------------------------------------------------------------
// Maxmod Stream Callback
// ------------------------------------------------------------
mm_word mp3_stream_callback(mm_word length, mm_addr dest, mm_stream_formats format) {
    s16* output = (s16*)dest;
    mm_word samples_filled = 0;

    while (samples_filled < length) {
        
        // 1. If we have leftover samples from the last decode, use them FIRST
        if (leftoverCount > 0) {
            int to_copy = leftoverCount;
            if (samples_filled + to_copy > length) {
                to_copy = length - samples_filled; // Don't overflow Maxmod's request
            }

            for (int i = 0; i < to_copy; i++) {
                *output++ = leftoverBuffer[(leftoverIndex * 2)];     // Left
                *output++ = leftoverBuffer[(leftoverIndex * 2) + 1]; // Right
                leftoverIndex++;
            }
            
            leftoverCount -= to_copy;
            samples_filled += to_copy;
            continue; // Loop back up to see if Maxmod still needs more data
        }

        // 2. If we are out of leftovers, decode the next MP3 frame
        if (mad_frame_decode(&madFrame, &madStream) != 0) {
            if (MAD_RECOVERABLE(madStream.error)) continue;
            
            // Loop the song if we hit the end of the file data
            if (madStream.error == MAD_ERROR_BUFLEN) {
                mad_stream_buffer(&madStream, song_mp3, song_mp3_size);
                continue; // Instantly jump back to the top of the while loop to decode the first frame!
            }

            break; // It's a true fatal error, stop decoding
        }

        mad_synth_frame(&madSynth, &madFrame);
        int decoded_samples = madSynth.pcm.length;
        bool isStereo = (madSynth.pcm.channels == 2);

        // 3. Store the newly decoded frame entirely into the leftover buffer
        leftoverIndex = 0;
        leftoverCount = decoded_samples;

        for (int i = 0; i < decoded_samples; i++) {
            s16 left = fixedToS16(madSynth.pcm.samples[0][i]);
            s16 right = isStereo ? fixedToS16(madSynth.pcm.samples[1][i]) : left;
            
            leftoverBuffer[i * 2] = left;
            leftoverBuffer[(i * 2) + 1] = right;
        }
        
        // Loop will immediately restart, hit Step 1, and copy from these new leftovers
    }
    
    return samples_filled; 
}

void mp3Cleanup() {
    mad_synth_finish(&madSynth);
    mad_frame_finish(&madFrame);
    mad_stream_finish(&madStream);
}

void MusicView::Init() {
    consoleDemoInit();  

    iprintf("MP3 Demo (Maxmod Streaming)\n");
    iprintf("Initialising...\n");

    // ----------------------------------------------------------------
    // 1. Initialize Maxmod WITHOUT a soundbank
    // ----------------------------------------------------------------
    mm_ds_system sys;
    sys.mod_count   = 0;
    sys.samp_count  = 0;
    sys.mem_bank    = 0;
    mmInit(&sys);

    // Point libmad at our embedded MP3 data
    mp3Init();

    iprintf("Decoding first frame...\n");

    // Decode one frame manually to establish the sample rate
    while (mad_frame_decode(&madFrame, &madStream) != 0) {
        if (!MAD_RECOVERABLE(madStream.error)) {
            iprintf("Error or empty file!\n");
            while(1) swiWaitForVBlank();
        }
    }
    mad_synth_frame(&madSynth, &madFrame);

    int sampleRate = madSynth.pcm.samplerate;
    iprintf("Sample rate: %d Hz\n", sampleRate);
    iprintf("Playing...\n");

    // Reset leftover buffer tracking before starting playback
    leftoverCount = 0;
    leftoverIndex = 0;

    // ----------------------------------------------------------------
    // 2. Configure Stream for MANUAL updates
    // ----------------------------------------------------------------
    mm_stream stream;
    stream.timer         = MM_TIMER0;               
    stream.sampling_rate = sampleRate;              
    stream.buffer_length = 2304;                    
    stream.callback      = mp3_stream_callback;     
    stream.format        = MM_STREAM_16BIT_STEREO;  
    stream.manual        = true; // Use manual filling so we control when it updates

    mmStreamOpen(&stream);
}

ViewState MusicView::Update() {
    swiWaitForVBlank();
    scanKeys();

    if (keysDown() & KEY_START) {
        return ViewState::MAIN_MENU;
    }

    // ----------------------------------------------------------------
    // 3. Update the stream manually every frame
    // ----------------------------------------------------------------
    mmStreamUpdate(); 

    return ViewState::KEEP_CURRENT;
}

void MusicView::Cleanup() {
    setBrightness(3, 0);
    consoleClear();

    mmStreamClose();
    mp3Cleanup();
}