#!/usr/bin/env python3
"""
texture2collision.py - Blockbench texture to DS collision map converter
Usage:
    python3 texture2collision.py <texture.png> <output.h> [x] [y] [width] [height]

Examples:
    # Full image
    python3 texture2collision.py texture.png map_data.h

    # Crop region (left, top, width, height)
    python3 texture2collision.py texture.png map_data.h 0 0 64 64
"""

import sys
import os

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install it with:")
    print("  pip install Pillow")
    sys.exit(1)


# ─── Tile color definitions ───────────────────────────────────────────────────
# Edit these to match the colors you painted in Blockbench.
# Format: (R, G, B): tile_value
TILE_COLORS = {
    # WORLD
    (197, 0, 0): 1,         # Collision
    (197, 194, 0): 2,       # Save
    (0, 92, 197): 3,        # Prev Scene
    (56, 197, 0): 4,        # Next Scene
    # CHARACTERS
    (0, 197, 173): 100,     # Character 1
    # (197, 0, 0): 101,     # Character 2
    # (197, 0, 0): 102,     # Character 3
    # ENEMIES
    # (197, 0, 0): 201,   # Enemy 1
    # (197, 0, 0): 202,   # Enemy 2
    # (197, 0, 0): 203,   # Enemy 3
}
DEFAULT_TILE = 0           # Any unrecognised color = walkable
COLOR_TOLERANCE = 10       # How close a color needs to be to match (0 = exact)
# ─────────────────────────────────────────────────────────────────────────────


def color_matches(pixel, target, tolerance):
    return all(abs(pixel[i] - target[i]) <= tolerance for i in range(3))


def pixel_to_tile(r, g, b):
    for color, tile_id in TILE_COLORS.items():
        if color_matches((r, g, b), color, COLOR_TOLERANCE):
            return tile_id
    return DEFAULT_TILE


def convert(input_path, output_path, crop=None):
    if not os.path.isfile(input_path):
        print(f"Error: File not found: {input_path}")
        sys.exit(1)

    img = Image.open(input_path).convert("RGB")

    if crop:
        x, y, w, h = crop
        img = img.crop((x, y, x + w, y + h))
        print(f"Cropped to region: x={x}, y={y}, w={w}, h={h}")

    # Flip vertically and horizontally to match the flip applied in obj2bin:
    # Without this, the collision map would be mirrored relative to the 3D model.
    img = img.transpose(Image.ROTATE_180)

    width, height = img.size
    print(f"Map size: {width}x{height} tiles")

    # Build the tile grid
    rows = []
    for row_y in range(height):
        row = []
        for col_x in range(width):
            r, g, b = img.getpixel((col_x, row_y))
            row.append(pixel_to_tile(r, g, b))
        rows.append(row)

    # Write the header file
    guard = os.path.basename(output_path).upper().replace(".", "_").replace("-", "_")

    with open(output_path, "w") as f:
        f.write(f"// Auto-generated by texture2collision.py — do not edit manually\n")
        f.write(f"// Source: {os.path.basename(input_path)}\n\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write(f"#include <stdint.h>\n\n")
        f.write(f"#define MAP_WIDTH  {width}\n")
        f.write(f"#define MAP_HEIGHT {height}\n\n")

        # Tile value legend as a comment
        f.write("// Tile values:\n")
        f.write(f"//   {DEFAULT_TILE} = walkable (default)\n")
        for color, tile_id in TILE_COLORS.items():
            f.write(f"//   {tile_id} = RGB{color}\n")
        f.write("\n")

        f.write(f"static const uint8_t collision_map[MAP_HEIGHT][MAP_WIDTH] = {{\n")
        for row in rows:
            f.write("    {" + ", ".join(str(t) for t in row) + "},\n")
        f.write("};\n\n")
        f.write(f"#endif // {guard}\n")

    print(f"Written to: {output_path}")


def print_usage():
    print(__doc__)


def main():
    args = sys.argv[1:]

    if len(args) < 2 or args[0] in ("-h", "--help"):
        print_usage()
        sys.exit(0)

    input_path  = args[0]
    output_path = args[1]
    crop        = None

    if len(args) == 6:
        try:
            x, y, w, h = int(args[2]), int(args[3]), int(args[4]), int(args[5])
            crop = (x, y, w, h)
        except ValueError:
            print("Error: Crop values must be integers: x y width height")
            sys.exit(1)
    elif len(args) not in (2, 6):
        print("Error: Wrong number of arguments.")
        print_usage()
        sys.exit(1)

    convert(input_path, output_path, crop)


if __name__ == "__main__":
    main()