#pragma once
// Auto-generated by dialogue_compiler.py — do not edit by hand
// Scene: demo

#include "controllers/DialogueController.h"

// ── Shared BG slot ──────────────────────────────────────────────────
// All dialogue bgs are swapped in/out of this one hardware slot.
// Assign this before calling any interaction _load():
//   demo_dialogue_bg_slot = bgInit(3, BgType_Text8bpp, BgSize_T_256x256, 0, 1);
extern int demo_dialogue_bg_slot;

void  demo_unload();  // stub: hide/free the slot

// ── interaction: yuki_guard_argument — Yuki arguing with a guard at the gate
//    bgs (4): [0]=bgGuard, [1]=bgYuki, [2]=bgAkihiko, [3]=bgYukiClose
extern const char*  demo_yuki_guard_argument_bg_names[4];
extern void        (*demo_yuki_guard_argument_bg_loaders[4])();
void  demo_yuki_guard_argument_load_bg(int bgIndex);
extern dialogue demo_yuki_guard_argument_lines[18];
void  demo_yuki_guard_argument_init();
void  demo_yuki_guard_argument_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* demo_yuki_guard_argument_first() { return &demo_yuki_guard_argument_lines[0]; }
inline dialogue* demo_yuki_guard_argument_vouch() { return &demo_yuki_guard_argument_lines[7]; }
inline dialogue* demo_yuki_guard_argument_side_guard() { return &demo_yuki_guard_argument_lines[12]; }
inline dialogue* demo_yuki_guard_argument_stay_out() { return &demo_yuki_guard_argument_lines[15]; }

// Initialise every interaction's struct arrays (call after all _load()s).
inline void demo_init_all() {
    demo_yuki_guard_argument_init();
}
