#pragma once
// Auto-generated by dialogue_compiler.py — do not edit by hand
// Scene: democomplex

#include "controllers/DialogueController.h"

// ── Shared BG slot ──────────────────────────────────────────────────
// All dialogue bgs are swapped in/out of this one hardware slot.
// Assign this before calling any interaction _load():
//   democomplex_dialogue_bg_slot = bgInit(3, BgType_Text8bpp, BgSize_T_256x256, 0, 1);
extern int democomplex_dialogue_bg_slot;

void  democomplex_unload();  // stub: hide/free the slot

// ── interaction: old_man — Old man sitting on the bench
//    bgs (1): [0]=bgBench
extern const char*  democomplex_old_man_bg_names[1];
extern void        (*democomplex_old_man_bg_loaders[1])();
void  democomplex_old_man_load_bg(int bgIndex);
extern dialogue democomplex_old_man_lines[4];
void  democomplex_old_man_init();
void  democomplex_old_man_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* democomplex_old_man_first() { return &democomplex_old_man_lines[0]; }

// ── interaction: akihiko_meets_yuki — Akihiko finds Yuki at the fountain
//    bgs (3): [0]=bgAkihiko, [1]=bgYuki, [2]=bgYukiClose
extern const char*  democomplex_akihiko_meets_yuki_bg_names[3];
extern void        (*democomplex_akihiko_meets_yuki_bg_loaders[3])();
void  democomplex_akihiko_meets_yuki_load_bg(int bgIndex);
extern dialogue democomplex_akihiko_meets_yuki_lines[8];
void  democomplex_akihiko_meets_yuki_init();
void  democomplex_akihiko_meets_yuki_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* democomplex_akihiko_meets_yuki_first() { return &democomplex_akihiko_meets_yuki_lines[0]; }

// ── interaction: hana_request — Hana asks the player for a favour
//    bgs (2): [0]=bgHana, [1]=bgHanaSad
extern const char*  democomplex_hana_request_bg_names[2];
extern void        (*democomplex_hana_request_bg_loaders[2])();
void  democomplex_hana_request_load_bg(int bgIndex);
extern dialogue democomplex_hana_request_lines[14];
void  democomplex_hana_request_init();
void  democomplex_hana_request_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* democomplex_hana_request_first() { return &democomplex_hana_request_lines[0]; }
inline dialogue* democomplex_hana_request_hana_agree() { return &democomplex_hana_request_lines[4]; }
inline dialogue* democomplex_hana_request_hana_decline() { return &democomplex_hana_request_lines[7]; }
inline dialogue* democomplex_hana_request_hana_negotiate() { return &democomplex_hana_request_lines[9]; }
inline dialogue* democomplex_hana_request_hana_deal_yes() { return &democomplex_hana_request_lines[12]; }

// ── interaction: yuki_guard_argument — Yuki arguing with a guard at the gate
//    bgs (4): [0]=bgGuard, [1]=bgYuki, [2]=bgAkihiko, [3]=bgYukiClose
extern const char*  democomplex_yuki_guard_argument_bg_names[4];
extern void        (*democomplex_yuki_guard_argument_bg_loaders[4])();
void  democomplex_yuki_guard_argument_load_bg(int bgIndex);
extern dialogue democomplex_yuki_guard_argument_lines[18];
void  democomplex_yuki_guard_argument_init();
void  democomplex_yuki_guard_argument_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* democomplex_yuki_guard_argument_first() { return &democomplex_yuki_guard_argument_lines[0]; }
inline dialogue* democomplex_yuki_guard_argument_vouch() { return &democomplex_yuki_guard_argument_lines[7]; }
inline dialogue* democomplex_yuki_guard_argument_side_guard() { return &democomplex_yuki_guard_argument_lines[12]; }
inline dialogue* democomplex_yuki_guard_argument_stay_out() { return &democomplex_yuki_guard_argument_lines[15]; }

// ── interaction: merchant_greeting — Travelling merchant near the east gate
//    bgs (2): [0]=bgShop, [1]=bgMerchantLean
extern const char*  democomplex_merchant_greeting_bg_names[2];
extern void        (*democomplex_merchant_greeting_bg_loaders[2])();
void  democomplex_merchant_greeting_load_bg(int bgIndex);
extern dialogue democomplex_merchant_greeting_lines[14];
void  democomplex_merchant_greeting_init();
void  democomplex_merchant_greeting_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* democomplex_merchant_greeting_first() { return &democomplex_merchant_greeting_lines[0]; }
inline dialogue* democomplex_merchant_greeting_merch_curious() { return &democomplex_merchant_greeting_lines[3]; }
inline dialogue* democomplex_merchant_greeting_merch_price() { return &democomplex_merchant_greeting_lines[7]; }
inline dialogue* democomplex_merchant_greeting_merch_maps() { return &democomplex_merchant_greeting_lines[9]; }
inline dialogue* democomplex_merchant_greeting_merch_bye() { return &democomplex_merchant_greeting_lines[12]; }

// ── interaction: notice_board — Wooden notice board near the fountain
//    bgs (1): [0]=bgBoard
extern const char*  democomplex_notice_board_bg_names[1];
extern void        (*democomplex_notice_board_bg_loaders[1])();
void  democomplex_notice_board_load_bg(int bgIndex);
extern dialogue democomplex_notice_board_lines[4];
void  democomplex_notice_board_init();
void  democomplex_notice_board_load();    // stub: fill bg_loaders[], call _init()
inline dialogue* democomplex_notice_board_first() { return &democomplex_notice_board_lines[0]; }

// Initialise every interaction's struct arrays (call after all _load()s).
inline void democomplex_init_all() {
    democomplex_old_man_init();
    democomplex_akihiko_meets_yuki_init();
    democomplex_hana_request_init();
    democomplex_yuki_guard_argument_init();
    democomplex_merchant_greeting_init();
    democomplex_notice_board_init();
}
