#include <nds.h>
#include "democomplex_dialogue.h"

// Auto-generated by dialogue_compiler.py — do not edit by hand
// Scene: democomplex

// ── Shared BG slot ──────────────────────────────────────────────────
int democomplex_dialogue_bg_slot = 0;

// ── BG imports ──────────────────────────────────────────────────────
#include "bgHanaSad.h"
#include "bgYukiClose.h"
#include "bgAkihiko.h"
#include "bgBench.h"
#include "bgGuard.h"
#include "bgMerchantLean.h"
#include "bgBoard.h"
#include "bgHana.h"
#include "bgShop.h"
#include "bgYuki.h"

void democomplex_unload() {
    bgHide(democomplex_dialogue_bg_slot);
    // TODO: free VRAM / reset loaders if needed.
}

// ════════════════════════════════════════════════════════════════
// interaction: old_man — Old man sitting on the bench
// ════════════════════════════════════════════════════════════════

const char* democomplex_old_man_bg_names[1] = { "bgBench" };
void (*democomplex_old_man_bg_loaders[1])() = {
    nullptr,  // [0] bgBench
};

void democomplex_old_man_load_bg(int bgIndex) {
    if (bgIndex >= 0 && bgIndex < 1 && democomplex_old_man_bg_loaders[bgIndex])
        democomplex_old_man_bg_loaders[bgIndex]();
}

void democomplex_old_man_load() {
    // Use democomplex_dialogue_bg_slot as the target hardware slot.
    
    democomplex_old_man_bg_loaders[0] = [](){
        dmaCopy(bgBenchTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgBenchTilesLen);
        dmaCopy(bgBenchMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgBenchMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgBenchPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgBenchPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };

    democomplex_old_man_init();
}

dialogue democomplex_old_man_lines[4];

void democomplex_old_man_init() {
    democomplex_old_man_lines[0] = { "OldMan", "Hm? A visitor. Haven't seen one of those in a while. ", 0 /* bgBench */, NULL, &democomplex_old_man_lines[1], {} };
    democomplex_old_man_lines[1] = { "OldMan", "This park used to be full of    children, you know. ", 0 /* bgBench */, &democomplex_old_man_lines[0], &democomplex_old_man_lines[2], {} };
    democomplex_old_man_lines[2] = { "OldMan", "Now it's just me and the        pigeons. ", 0 /* bgBench */, &democomplex_old_man_lines[1], &democomplex_old_man_lines[3], {} };
    democomplex_old_man_lines[3] = { "OldMan", "...Anyway. Don't mind me. Enjoy the view. ", 0 /* bgBench */, &democomplex_old_man_lines[2], NULL, {} };
}

// ════════════════════════════════════════════════════════════════
// interaction: akihiko_meets_yuki — Akihiko finds Yuki at the fountain
// ════════════════════════════════════════════════════════════════

const char* democomplex_akihiko_meets_yuki_bg_names[3] = { "bgAkihiko", "bgYuki", "bgYukiClose" };
void (*democomplex_akihiko_meets_yuki_bg_loaders[3])() = {
    nullptr,  // [0] bgAkihiko
    nullptr,  // [1] bgYuki
    nullptr,  // [2] bgYukiClose
};

void democomplex_akihiko_meets_yuki_load_bg(int bgIndex) {
    if (bgIndex >= 0 && bgIndex < 3 && democomplex_akihiko_meets_yuki_bg_loaders[bgIndex])
        democomplex_akihiko_meets_yuki_bg_loaders[bgIndex]();
}

void democomplex_akihiko_meets_yuki_load() {
    // Use democomplex_dialogue_bg_slot as the target hardware slot.
    
    democomplex_akihiko_meets_yuki_bg_loaders[0] = [](){
        dmaCopy(bgAkihikoTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgAkihikoTilesLen);
        dmaCopy(bgAkihikoMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgAkihikoMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgAkihikoPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgAkihikoPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };
    
    democomplex_akihiko_meets_yuki_bg_loaders[1] = [](){
        dmaCopy(bgYukiTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgYukiTilesLen);
        dmaCopy(bgYukiMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgYukiMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgYukiPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgYukiPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };
    
    democomplex_akihiko_meets_yuki_bg_loaders[2] = [](){
        dmaCopy(bgYukiCloseTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgYukiCloseTilesLen);
        dmaCopy(bgYukiCloseMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgYukiCloseMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgYukiClosePal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgYukiClosePalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };

    democomplex_akihiko_meets_yuki_init();
}

dialogue democomplex_akihiko_meets_yuki_lines[8];

void democomplex_akihiko_meets_yuki_init() {
    democomplex_akihiko_meets_yuki_lines[0] = { "Akihiko", "Hey — I thought that was you. ", 0 /* bgAkihiko */, NULL, &democomplex_akihiko_meets_yuki_lines[1], {} };
    democomplex_akihiko_meets_yuki_lines[1] = { "Yuki", "Oh. Akihiko. You're the last    person I expected to see here. ", 1 /* bgYuki */, &democomplex_akihiko_meets_yuki_lines[0], &democomplex_akihiko_meets_yuki_lines[2], {} };
    democomplex_akihiko_meets_yuki_lines[2] = { "Akihiko", "I could say the same. You       actually left your room? ", 0 /* bgAkihiko */, &democomplex_akihiko_meets_yuki_lines[1], &democomplex_akihiko_meets_yuki_lines[3], {} };
    democomplex_akihiko_meets_yuki_lines[3] = { "Yuki", "Ha ha. Very funny. ", 1 /* bgYuki */, &democomplex_akihiko_meets_yuki_lines[2], &democomplex_akihiko_meets_yuki_lines[4], {} };
    democomplex_akihiko_meets_yuki_lines[4] = { "Yuki", "I come here to think. The noise back home is… a lot. ", 2 /* bgYukiClose */, &democomplex_akihiko_meets_yuki_lines[3], &democomplex_akihiko_meets_yuki_lines[5], {} };
    democomplex_akihiko_meets_yuki_lines[5] = { "Akihiko", "Yeah. I get that. ", 0 /* bgAkihiko */, &democomplex_akihiko_meets_yuki_lines[4], &democomplex_akihiko_meets_yuki_lines[6], {} };
    democomplex_akihiko_meets_yuki_lines[6] = { "Akihiko", "I won't bother you then. Just   wanted to say hi. ", 0 /* bgAkihiko */, &democomplex_akihiko_meets_yuki_lines[5], &democomplex_akihiko_meets_yuki_lines[7], {} };
    democomplex_akihiko_meets_yuki_lines[7] = { "Yuki", "...You can stay. If you want. ", 1 /* bgYuki */, &democomplex_akihiko_meets_yuki_lines[6], NULL, {} };
}

// ════════════════════════════════════════════════════════════════
// interaction: hana_request — Hana asks the player for a favour
// ════════════════════════════════════════════════════════════════

const char* democomplex_hana_request_bg_names[2] = { "bgHana", "bgHanaSad" };
void (*democomplex_hana_request_bg_loaders[2])() = {
    nullptr,  // [0] bgHana
    nullptr,  // [1] bgHanaSad
};

void democomplex_hana_request_load_bg(int bgIndex) {
    if (bgIndex >= 0 && bgIndex < 2 && democomplex_hana_request_bg_loaders[bgIndex])
        democomplex_hana_request_bg_loaders[bgIndex]();
}

void democomplex_hana_request_load() {
    // Use democomplex_dialogue_bg_slot as the target hardware slot.
    
    democomplex_hana_request_bg_loaders[0] = [](){
        dmaCopy(bgHanaTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgHanaTilesLen);
        dmaCopy(bgHanaMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgHanaMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgHanaPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgHanaPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };
    
    democomplex_hana_request_bg_loaders[1] = [](){
        dmaCopy(bgHanaSadTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgHanaSadTilesLen);
        dmaCopy(bgHanaSadMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgHanaSadMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgHanaSadPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgHanaSadPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };

    democomplex_hana_request_init();
}

dialogue democomplex_hana_request_lines[14];

void democomplex_hana_request_init() {
    dialogueSelection democomplex_hana_request_sel_3_0 = { "Sure, I'll look into it.", false, &democomplex_hana_request_lines[4] };
    dialogueSelection democomplex_hana_request_sel_3_1 = { "Sorry, I'm busy right now", false, &democomplex_hana_request_lines[7] };
    dialogueSelection democomplex_hana_request_sel_3_2 = { "What's it worth to you?", false, &democomplex_hana_request_lines[9] };
    dialogueSelection democomplex_hana_request_sel_11_0 = { "Deal.", false, &democomplex_hana_request_lines[12] };
    dialogueSelection democomplex_hana_request_sel_11_1 = { "No thanks", false, &democomplex_hana_request_lines[7] };

    democomplex_hana_request_lines[0] = { "Hana", "Oh! You're here — perfect       timing. ", 0 /* bgHana */, NULL, &democomplex_hana_request_lines[1], {} };
    democomplex_hana_request_lines[1] = { "Hana", "I've been trying to figure out  where the flower market moved   to. ", 0 /* bgHana */, &democomplex_hana_request_lines[0], &democomplex_hana_request_lines[2], {} };
    democomplex_hana_request_lines[2] = { "Hana", "I heard it's somewhere on the   east side now, but I'm not sure. ", 0 /* bgHana */, &democomplex_hana_request_lines[1], &democomplex_hana_request_lines[3], {} };
    democomplex_hana_request_lines[3] = { "Hana", "Could you help me track it down? ", 0 /* bgHana */, &democomplex_hana_request_lines[2], NULL, { democomplex_hana_request_sel_3_0, democomplex_hana_request_sel_3_1, democomplex_hana_request_sel_3_2 } };
    democomplex_hana_request_lines[4] = { "Hana", "Really? Thank you so much! ", 0 /* bgHana */, &democomplex_hana_request_lines[3], &democomplex_hana_request_lines[5], {} };  // @hana_agree
    democomplex_hana_request_lines[5] = { "Hana", "I need white peonies. The       florist on Elm Street used to   carry them. ", 0 /* bgHana */, &democomplex_hana_request_lines[4], &democomplex_hana_request_lines[6], {} };
    democomplex_hana_request_lines[6] = { "Hana", "I'll be at the north gate if you find anything. ", 0 /* bgHana */, &democomplex_hana_request_lines[5], NULL, {} };
    democomplex_hana_request_lines[7] = { "Hana", "Oh… that's alright. I'll figure it out myself. ", 0 /* bgHana */, &democomplex_hana_request_lines[6], &democomplex_hana_request_lines[8], {} };  // @hana_decline
    democomplex_hana_request_lines[8] = { "Hana", "I always do. ", 1 /* bgHanaSad */, &democomplex_hana_request_lines[7], NULL, {} };
    democomplex_hana_request_lines[9] = { "Hana", "...Ha. Direct. I like that. ", 0 /* bgHana */, &democomplex_hana_request_lines[8], &democomplex_hana_request_lines[10], {} };  // @hana_negotiate
    democomplex_hana_request_lines[10] = { "Hana", "How about this — I'll make you  lunch if you find the place. ", 0 /* bgHana */, &democomplex_hana_request_lines[9], &democomplex_hana_request_lines[11], {} };
    democomplex_hana_request_lines[11] = { "Hana", "Deal? ", 0 /* bgHana */, &democomplex_hana_request_lines[10], NULL, { democomplex_hana_request_sel_11_0, democomplex_hana_request_sel_11_1 } };
    democomplex_hana_request_lines[12] = { "Hana", "Perfect. I make excellent       tamagoyaki, just so you know. ", 0 /* bgHana */, &democomplex_hana_request_lines[11], &democomplex_hana_request_lines[13], {} };  // @hana_deal_yes
    democomplex_hana_request_lines[13] = { "Hana", "White peonies. North gate. Don't forget! ", 0 /* bgHana */, &democomplex_hana_request_lines[12], NULL, {} };
}

// ════════════════════════════════════════════════════════════════
// interaction: yuki_guard_argument — Yuki arguing with a guard at the gate
// ════════════════════════════════════════════════════════════════

const char* democomplex_yuki_guard_argument_bg_names[4] = { "bgGuard", "bgYuki", "bgAkihiko", "bgYukiClose" };
void (*democomplex_yuki_guard_argument_bg_loaders[4])() = {
    nullptr,  // [0] bgGuard
    nullptr,  // [1] bgYuki
    nullptr,  // [2] bgAkihiko
    nullptr,  // [3] bgYukiClose
};

void democomplex_yuki_guard_argument_load_bg(int bgIndex) {
    if (bgIndex >= 0 && bgIndex < 4 && democomplex_yuki_guard_argument_bg_loaders[bgIndex])
        democomplex_yuki_guard_argument_bg_loaders[bgIndex]();
}

void democomplex_yuki_guard_argument_load() {
    // Use democomplex_dialogue_bg_slot as the target hardware slot.
    
    democomplex_yuki_guard_argument_bg_loaders[0] = [](){
        dmaCopy(bgGuardTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgGuardTilesLen);
        dmaCopy(bgGuardMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgGuardMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgGuardPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgGuardPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };
    
    democomplex_yuki_guard_argument_bg_loaders[1] = [](){
        dmaCopy(bgYukiTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgYukiTilesLen);
        dmaCopy(bgYukiMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgYukiMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgYukiPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgYukiPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };
    
    democomplex_yuki_guard_argument_bg_loaders[2] = [](){
        dmaCopy(bgAkihikoTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgAkihikoTilesLen);
        dmaCopy(bgAkihikoMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgAkihikoMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgAkihikoPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgAkihikoPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };
    
    democomplex_yuki_guard_argument_bg_loaders[3] = [](){
        dmaCopy(bgYukiCloseTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgYukiCloseTilesLen);
        dmaCopy(bgYukiCloseMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgYukiCloseMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgYukiClosePal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgYukiClosePalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };

    democomplex_yuki_guard_argument_init();
}

dialogue democomplex_yuki_guard_argument_lines[18];

void democomplex_yuki_guard_argument_init() {
    dialogueSelection democomplex_yuki_guard_argument_sel_6_0 = { "Vouch for Yuki", false, &democomplex_yuki_guard_argument_lines[7] };
    dialogueSelection democomplex_yuki_guard_argument_sel_6_1 = { "Side with the guard", false, &democomplex_yuki_guard_argument_lines[12] };
    dialogueSelection democomplex_yuki_guard_argument_sel_6_2 = { "Stay out of it", false, &democomplex_yuki_guard_argument_lines[15] };

    democomplex_yuki_guard_argument_lines[0] = { "Guard", "Ma'am, the east path is closed  after sundown. I've said it     twice. ", 0 /* bgGuard */, NULL, &democomplex_yuki_guard_argument_lines[1], {} };
    democomplex_yuki_guard_argument_lines[1] = { "Yuki", "And I've told you — I left my   bag on the bench. It will take  thirty seconds. ", 1 /* bgYuki */, &democomplex_yuki_guard_argument_lines[0], &democomplex_yuki_guard_argument_lines[2], {} };
    democomplex_yuki_guard_argument_lines[2] = { "Guard", "Rules are rules. Come back      tomorrow. ", 0 /* bgGuard */, &democomplex_yuki_guard_argument_lines[1], &democomplex_yuki_guard_argument_lines[3], {} };
    democomplex_yuki_guard_argument_lines[3] = { "Akihiko", "Hey, what's going on? ", 2 /* bgAkihiko */, &democomplex_yuki_guard_argument_lines[2], &democomplex_yuki_guard_argument_lines[4], {} };
    democomplex_yuki_guard_argument_lines[4] = { "Yuki", "This guard won't let me through to get my bag. ", 1 /* bgYuki */, &democomplex_yuki_guard_argument_lines[3], &democomplex_yuki_guard_argument_lines[5], {} };
    democomplex_yuki_guard_argument_lines[5] = { "Guard", "Sir, please stay back. This     doesn't concern you. ", 0 /* bgGuard */, &democomplex_yuki_guard_argument_lines[4], &democomplex_yuki_guard_argument_lines[6], {} };
    democomplex_yuki_guard_argument_lines[6] = { "Akihiko", "Can we work something out here? ", 2 /* bgAkihiko */, &democomplex_yuki_guard_argument_lines[5], NULL, { democomplex_yuki_guard_argument_sel_6_0, democomplex_yuki_guard_argument_sel_6_1, democomplex_yuki_guard_argument_sel_6_2 } };
    democomplex_yuki_guard_argument_lines[7] = { "Akihiko", "I know her. She's not going to  cause any trouble. ", 2 /* bgAkihiko */, &democomplex_yuki_guard_argument_lines[6], &democomplex_yuki_guard_argument_lines[8], {} };  // @vouch
    democomplex_yuki_guard_argument_lines[8] = { "Guard", "... ", 0 /* bgGuard */, &democomplex_yuki_guard_argument_lines[7], &democomplex_yuki_guard_argument_lines[9], {} };
    democomplex_yuki_guard_argument_lines[9] = { "Guard", "Fine. Two minutes. And you're   coming with her. ", 0 /* bgGuard */, &democomplex_yuki_guard_argument_lines[8], &democomplex_yuki_guard_argument_lines[10], {} };
    democomplex_yuki_guard_argument_lines[10] = { "Yuki", "Thank you. ", 1 /* bgYuki */, &democomplex_yuki_guard_argument_lines[9], &democomplex_yuki_guard_argument_lines[11], {} };
    democomplex_yuki_guard_argument_lines[11] = { "Yuki", "...Both of you. ", 3 /* bgYukiClose */, &democomplex_yuki_guard_argument_lines[10], NULL, {} };
    democomplex_yuki_guard_argument_lines[12] = { "Akihiko", "He's got a point, Yuki. Come    back in the morning. ", 2 /* bgAkihiko */, &democomplex_yuki_guard_argument_lines[11], &democomplex_yuki_guard_argument_lines[13], {} };  // @side_guard
    democomplex_yuki_guard_argument_lines[13] = { "Yuki", "Are you serious right now? ", 1 /* bgYuki */, &democomplex_yuki_guard_argument_lines[12], &democomplex_yuki_guard_argument_lines[14], {} };
    democomplex_yuki_guard_argument_lines[14] = { "Yuki", "Fine. Don't talk to me tonight. ", 3 /* bgYukiClose */, &democomplex_yuki_guard_argument_lines[13], NULL, {} };
    democomplex_yuki_guard_argument_lines[15] = { "Akihiko", "Actually — yeah, none of my     business. Carry on. ", 2 /* bgAkihiko */, &democomplex_yuki_guard_argument_lines[14], &democomplex_yuki_guard_argument_lines[16], {} };  // @stay_out
    democomplex_yuki_guard_argument_lines[16] = { "Guard", "Smart man. ", 0 /* bgGuard */, &democomplex_yuki_guard_argument_lines[15], &democomplex_yuki_guard_argument_lines[17], {} };
    democomplex_yuki_guard_argument_lines[17] = { "Yuki", "Unbelievable. ", 1 /* bgYuki */, &democomplex_yuki_guard_argument_lines[16], NULL, {} };
}

// ════════════════════════════════════════════════════════════════
// interaction: merchant_greeting — Travelling merchant near the east gate
// ════════════════════════════════════════════════════════════════

const char* democomplex_merchant_greeting_bg_names[2] = { "bgShop", "bgMerchantLean" };
void (*democomplex_merchant_greeting_bg_loaders[2])() = {
    nullptr,  // [0] bgShop
    nullptr,  // [1] bgMerchantLean
};

void democomplex_merchant_greeting_load_bg(int bgIndex) {
    if (bgIndex >= 0 && bgIndex < 2 && democomplex_merchant_greeting_bg_loaders[bgIndex])
        democomplex_merchant_greeting_bg_loaders[bgIndex]();
}

void democomplex_merchant_greeting_load() {
    // Use democomplex_dialogue_bg_slot as the target hardware slot.
    
    democomplex_merchant_greeting_bg_loaders[0] = [](){
        dmaCopy(bgShopTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgShopTilesLen);
        dmaCopy(bgShopMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgShopMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgShopPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgShopPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };
    
    democomplex_merchant_greeting_bg_loaders[1] = [](){
        dmaCopy(bgMerchantLeanTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgMerchantLeanTilesLen);
        dmaCopy(bgMerchantLeanMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgMerchantLeanMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgMerchantLeanPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgMerchantLeanPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };

    democomplex_merchant_greeting_init();
}

dialogue democomplex_merchant_greeting_lines[14];

void democomplex_merchant_greeting_init() {
    dialogueSelection democomplex_merchant_greeting_sel_2_0 = { "What kind of curiosities?", false, &democomplex_merchant_greeting_lines[3] };
    dialogueSelection democomplex_merchant_greeting_sel_2_1 = { "Tell me about the maps.", false, &democomplex_merchant_greeting_lines[9] };
    dialogueSelection democomplex_merchant_greeting_sel_2_2 = { "Just browsing, thanks.", false, &democomplex_merchant_greeting_lines[12] };
    dialogueSelection democomplex_merchant_greeting_sel_6_0 = { "How much?", false, &democomplex_merchant_greeting_lines[7] };
    dialogueSelection democomplex_merchant_greeting_sel_6_1 = { "No thanks.", false, &democomplex_merchant_greeting_lines[12] };

    democomplex_merchant_greeting_lines[0] = { "Merchant", "Welcome, welcome! Looking for   anything in particular? ", 0 /* bgShop */, NULL, &democomplex_merchant_greeting_lines[1], {} };
    democomplex_merchant_greeting_lines[1] = { "Merchant", "I've got maps, dried goods, and a few… curiosities. ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[0], &democomplex_merchant_greeting_lines[2], {} };
    democomplex_merchant_greeting_lines[2] = { "Merchant", "What catches your eye? ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[1], NULL, { democomplex_merchant_greeting_sel_2_0, democomplex_merchant_greeting_sel_2_1, democomplex_merchant_greeting_sel_2_2 } };
    democomplex_merchant_greeting_lines[3] = { "Merchant", "Ah, a person of taste! ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[2], &democomplex_merchant_greeting_lines[4], {} };  // @merch_curious
    democomplex_merchant_greeting_lines[4] = { "Merchant", "I've got a compass that always  points to your greatest regret. ", 1 /* bgMerchantLean */, &democomplex_merchant_greeting_lines[3], &democomplex_merchant_greeting_lines[5], {} };
    democomplex_merchant_greeting_lines[5] = { "Merchant", "Terrible for navigation.        Wonderful for drama. ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[4], &democomplex_merchant_greeting_lines[6], {} };
    democomplex_merchant_greeting_lines[6] = { "Merchant", "Interested? ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[5], NULL, { democomplex_merchant_greeting_sel_6_0, democomplex_merchant_greeting_sel_6_1 } };
    democomplex_merchant_greeting_lines[7] = { "Merchant", "For you? Three silver. ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[6], &democomplex_merchant_greeting_lines[8], {} };  // @merch_price
    democomplex_merchant_greeting_lines[8] = { "Merchant", "Or one favour. I'll let you     decide which is cheaper. ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[7], NULL, {} };
    democomplex_merchant_greeting_lines[9] = { "Merchant", "Best maps this side of the      river! ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[8], &democomplex_merchant_greeting_lines[10], {} };  // @merch_maps
    democomplex_merchant_greeting_lines[10] = { "Merchant", "I've got the eastern districts, old town routes, even the       underground canals. ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[9], &democomplex_merchant_greeting_lines[11], {} };
    democomplex_merchant_greeting_lines[11] = { "Merchant", "The canal map's not strictly…   legal to own. But that's between us. ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[10], NULL, {} };
    democomplex_merchant_greeting_lines[12] = { "Merchant", "No trouble at all. Come back    anytime! ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[11], &democomplex_merchant_greeting_lines[13], {} };  // @merch_bye
    democomplex_merchant_greeting_lines[13] = { "Merchant", "I'll be here until the lanterns go out. ", 0 /* bgShop */, &democomplex_merchant_greeting_lines[12], NULL, {} };
}

// ════════════════════════════════════════════════════════════════
// interaction: notice_board — Wooden notice board near the fountain
// ════════════════════════════════════════════════════════════════

const char* democomplex_notice_board_bg_names[1] = { "bgBoard" };
void (*democomplex_notice_board_bg_loaders[1])() = {
    nullptr,  // [0] bgBoard
};

void democomplex_notice_board_load_bg(int bgIndex) {
    if (bgIndex >= 0 && bgIndex < 1 && democomplex_notice_board_bg_loaders[bgIndex])
        democomplex_notice_board_bg_loaders[bgIndex]();
}

void democomplex_notice_board_load() {
    // Use democomplex_dialogue_bg_slot as the target hardware slot.
    
    democomplex_notice_board_bg_loaders[0] = [](){
        dmaCopy(bgBoardTiles,
            bgGetGfxPtr(democomplex_dialogue_bg_slot),
            bgBoardTilesLen);
        dmaCopy(bgBoardMap,
            bgGetMapPtr(democomplex_dialogue_bg_slot),
            bgBoardMapLen);
        vramSetBankH(VRAM_H_LCD);
        dmaCopy(bgBoardPal,
            &VRAM_H_EXT_PALETTE[0][0],
            bgBoardPalLen);
        vramSetBankH(VRAM_H_SUB_BG_EXT_PALETTE);
        bgShow(democomplex_dialogue_bg_slot);
    };

    democomplex_notice_board_init();
}

dialogue democomplex_notice_board_lines[4];

void democomplex_notice_board_init() {
    democomplex_notice_board_lines[0] = { "Sign", "[RIVERSIDE PARK — PUBLIC NOTICE] ", 0 /* bgBoard */, NULL, &democomplex_notice_board_lines[1], {} };
    democomplex_notice_board_lines[1] = { "Sign", "The east footpath will be closed for maintenance from sundown. ", 0 /* bgBoard */, &democomplex_notice_board_lines[0], &democomplex_notice_board_lines[2], {} };
    democomplex_notice_board_lines[2] = { "Sign", "Please use the north gate as an alternate route. ", 0 /* bgBoard */, &democomplex_notice_board_lines[1], &democomplex_notice_board_lines[3], {} };
    democomplex_notice_board_lines[3] = { "Sign", "Thank you for your cooperation. — Park Authority ", 0 /* bgBoard */, &democomplex_notice_board_lines[2], NULL, {} };
}
